# Generated by Django 6.0.6 on 2026-06-21 05:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residuos', '0002_alter_residuo_id'),
        ('usuarios', '0003_alter_usuario_total_reciclado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('kilos', models.FloatField()),
                ('ganancia_obtenida', models.FloatField()),
                ('otros', models.FloatField()),
                ('tipo_residuo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='residuos.residuo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
