# Generated by Django 6.0.6 on 2026-06-21 06:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residuos', '0002_alter_residuo_id'),
        ('usuarios', '0003_alter_usuario_total_reciclado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('INGRESO', 'Ingreso de material'), ('VENTA', 'Material reciclado/vendido'), ('PERDIDA', 'Pérdida o desperdicio')], default='INGRESO', max_length=10)),
                ('kilos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ganancia_obtenida', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tipo_residuo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='residuos.residuo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
