# Generated by Django 6.0.6 on 2026-06-21 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('usuarios', '0003_alter_usuario_total_reciclado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contabilidad',
            name='otros',
        ),
        migrations.AddField(
            model_name='contabilidad',
            name='tipo_movimiento',
            field=models.CharField(choices=[('INGRESO', 'Ingreso de material'), ('VENTA', 'Material reciclado/vendido'), ('PERDIDA', 'Pérdida o desperdicio')], default='INGRESO', max_length=10),
        ),
        migrations.AlterField(
            model_name='contabilidad',
            name='ganancia_obtenida',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contabilidad',
            name='kilos',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contabilidad',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
    ]
