# Generated by Django 6.0.6 on 2026-06-22 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('residuos', '0002_alter_residuo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contabilidad',
            name='tipo_residuo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='residuos.residuo'),
        ),
    ]
