# Generated by Django 6.0.6 on 2026-06-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='total_reciclado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
