# Generated by Django 6.0.6 on 2026-06-15 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_residuo_contabilidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contabilidad',
            name='tipo_residuo',
        ),
        migrations.RemoveField(
            model_name='contabilidad',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='residuo',
        ),
        migrations.DeleteModel(
            name='contabilidad',
        ),
    ]
